// This is an autogenerated file from Firebase Studio.

'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { JapaGenieLogo } from '@/components/icons';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { Menu } from 'lucide-react';
import { cn } from '@/lib/utils';

const menuItems = [
  { href: '/dashboard', label: 'Dashboard' },
  { href: '/progress', label: 'Progress Map' },
  { href: '/document-check', label: 'Document Checker' },
  { href: '/chat', label: 'AI Assistant' },
  { href: '/how-it-works', label: 'How It Works' },
  { href: '/features', label: 'Features' },
  { href: '/pricing', label: 'Pricing' },
];

export function AppHeader() {
  const pathname = usePathname();

  const NavLinks = ({ className }: { className?: string }) => (
    <nav className={cn('flex items-center gap-4 lg:gap-6', className)}>
      {menuItems.map((item) => (
        <Link
          key={item.href}
          href={item.href}
          className={cn(
            'transition-colors hover:text-primary',
            pathname === item.href ? 'text-primary font-semibold' : 'text-muted-foreground'
          )}
        >
          {item.label}
        </Link>
      ))}
    </nav>
  );

  return (
    <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-16 items-center">
        <Link href="/dashboard" className="mr-6 flex items-center gap-2">
          <JapaGenieLogo className="w-8 h-8 text-primary" />
          <span className="font-bold text-lg">Japa Genie</span>
        </Link>

        <div className="hidden md:flex flex-1 items-center justify-end space-x-4">
           <NavLinks className="text-sm" />
        </div>

        <div className="flex flex-1 items-center justify-end md:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="ghost" size="icon">
                <Menu className="h-6 w-6" />
                <span className="sr-only">Toggle Menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left">
                <div className="p-4">
                     <Link href="/dashboard" className="mb-8 flex items-center gap-2">
                        <JapaGenieLogo className="w-8 h-8 text-primary" />
                        <span className="font-bold text-lg">Japa Genie</span>
                    </Link>
                    <NavLinks className="flex-col items-start gap-6 text-lg" />
                </div>
            </SheetContent>
          </Sheet>
        </div>
      </div>
    </header>
  );
}
