// This is an autogenerated file from Firebase Studio.

import { Logo } from '@/components/icons';
import Link from 'next/link';

const footerSections = [
    {
        title: 'Product',
        links: [
            { label: 'Features', href: '/features' },
            { label: 'Pricing', href: '/pricing' },
            { label: 'How It Works', href: '/how-it-works' },
        ],
    },
    {
        title: 'Company',
        links: [
            { label: 'About Us', href: '#' },
            { label: 'Careers', href: '#' },
            { label: 'Contact', href: '#' },
        ],
    },
    {
        title: 'Legal',
        links: [
            { label: 'Privacy Policy', href: '#' },
            { label: 'Terms of Service', href: '#' },
        ],
    }
];

export function AppFooter() {
  return (
    <footer className="border-t bg-card text-card-foreground">
      <div className="container py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="flex flex-col gap-4 pr-8">
                 <Link href="/dashboard" className="flex items-center gap-2">
                    <Logo className="w-8 h-8 text-primary" />
                    <span className="font-bold text-lg">Japa Genie</span>
                </Link>
                <p className="text-sm text-muted-foreground">
                    Your AI-powered guide to seamless visa applications.
                </p>
            </div>
            {footerSections.map(section => (
                <div key={section.title}>
                    <h4 className="font-semibold mb-4">{section.title}</h4>
                    <ul className="space-y-2">
                        {section.links.map(link => (
                            <li key={link.label}>
                                <Link href={link.href} className="text-sm text-muted-foreground hover:text-primary transition-colors">
                                    {link.label}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>
            ))}
        </div>
        <div className="mt-12 pt-8 border-t text-center text-sm text-muted-foreground">
            <p>&copy; {new Date().getFullYear()} Japa Genie. All rights reserved.</p>
        </div>
      </div>
    </footer>
  );
}